language: php
php:
  - "7.4"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  
before_install:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - php ci/check_filters_docs.php || travis_terminate 1;
  - php ci/check_validators_docs.php || travis_terminate 1;
  - php ci/check_validators_translations.php || travis_terminate 1;

after_script:
  - travis_retry php vendor/bin/php-coveralls -v